### ISSUE TITLE
Multiple warnings on casts from type "const U32 *" to type "U8 *"

### ISSUE THREAD

**Issue by rmam-spinworks** [LASzip/LASzip#49]
While building LASzip, the build process throws a large number of warnings pointing out conversions from U8 to U32.  It would be nice if these warnings could be handled so that the build process could finish without throwing warnings.

**Comment by rmam-spinworks** [comment]
I've noticed the compiler warnings while building LASzip with a Ubuntu 16.04 system, which uses gcc 5.4.0. 

At first glance all the warnings indicate a single issue: casting pointers to const-qualified variables to pointer to non-const-qualified variables.  Here's an excerpt from the build's output:

```
/home/rmam/development/LASzip/src/laszip_dll.cpp:2204:51: warning: cast from type ‘const unsigned int*’ to type ‘U8* {aka unsigned char*}’ casts away qualifiers [-Wcast-qual]
   try { out->put32bitsLE((U8*)&(laszip->chunk_size)); } catch(...)
```

I assume that tweaking the type cast to include the const qualifier may be enough to get rid of the warnings, but I haven't checked this.  I can take a look into these warnings later in the day.

**Comment by rapidlasso** [comment]
Ok. This should be fixed by this commit here:

https://github.com/LASzip/LASzip/commit/55d441978967ed6fbb58492dd042264a96775f82

**Comment by rmam-spinworks** [comment]
I've just took a quick look at the project's master branch and unfortunately the build process still throws a long list of warnings (over 400) when building LASzip on Ubuntu 16.04 with gcc 5.4.0.  Most warnings point to qualifiers being casted away, but I've noticed some entries regarding implicit type conversions, using 0 as the null pointer constant, and passing unexpected argument types to sprintf().
